# Copyright (c) 2025 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

---
global_design_sites:
  - site:
      area:
        name: "{{ dnac_area }}"
        parent_name: Global
    type: area

network_management_details:
  - site_name: Global
    settings:
      dhcp_server:
        - "{{ dnac_dhcp }}"
      dns_server:
        domain_name: "{{ dnac_domain_name }}"
        primary_ip_address: "{{ dnac_dns_server }}"
      ntp_server:
        - "{{ dnac_ntp_server }}"
      timezone: "{{ dnac_timezone }}"
      snmp_server:
        configure_dnac_ip: true
      syslog_server:
        configure_dnac_ip: true

global_credential_details:
  cli_credential:
    - description: CLI
      username: "{{ dnac_cli_user }}"
      password: "{{ dnac_cli_password }}"
      enable_password: "{{ dnac_cli_password }}"
  snmp_v2c_read:
    - description: RO
      read_community: "{{ dnac_snmp_ro_community }}"
  snmp_v2c_write:
    - description: RW
      write_community: "{{ dnac_snmp_rw_community }}"

assign_credentials_to_site:
  Sync: false
  cli_credential:
    description: CLI
    username: "{{ dnac_cli_user }}"
  snmp_v2c_read:
    description: RO
  snmp_v2c_write:
    description: RW
  site_name:
    - "Global/{{ dnac_area }}"
